### ISSUE TITLE
What hobby of yours do you spend most of your money on.

### ISSUE THREAD

**Issue by AchoArnold** [SamVerschueren/ama#14]
After reading this https://github.com/SamVerschueren/ama/issues/11 I noticed you don't like spending money on gadgets. So what are you comfortable spending money on?

**Comment by SamVerschueren** [comment]
Not really hobbies in particular. I'd rather spend money for my daughter, go to a restaurant with my girlfriend or do something together with my family. Those things are much more important to me than the latest iPhone or smartwatch or something.

I hope this answers the question :).
