### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/ama#3]

**Comment by SamVerschueren** [comment]
I started getting interest into webdevelopment when I was 15 years old. It was pretty basic though. It where the typical ugly looking websites that everyone once created when they started doing some webdevelopment. Using tables to design your website, embed copy-pasted javascript code to add an analog clock to your mouse. The usual 90s website, good times :).

A little later (that same year) I started getting interest into programming. My sisters boyfrined was studying informatics and he gave me a Java book from his course. So I started programming command line Java applications in Eclipse and later on moved to Java Swing to create the most ugly looking user interface ever... After that I did some basic C++ and Assembler as well. I could litterly spend an entire day and night behind my computer to get something to work.
