### ISSUE TITLE
What is your favorite quote and why?

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/ama#5]

**Comment by SamVerschueren** [comment]
> "Get busy livin', or get busy dyin'" - Morgan Freeman

![quote](https://cloud.githubusercontent.com/assets/1913805/18377850/d83af552-7669-11e6-9a79-e8ff65e166ac.jpg)

First of all, I like the movie. Second of all, It really makes sense. Stop being depressed and start enjoying life. Don't be afraid of doing what you want and love to do. You only live once.
