### ISSUE TITLE
Do you like chicken?

### ISSUE THREAD

**Issue by sotojuan** [SamVerschueren/ama#6]
🐤

**Comment by SamVerschueren** [comment]
As food or alive? :p

**Comment by sotojuan** [comment]
Both!

**Comment by SamVerschueren** [comment]
I'm not really an animal person. So alive, not really. Some neighbour also has a rooster, and it wakes me up way too early in the summertimes. He probably screwed up for the other chickens. 

As food, yes. But I don't like it when I have to eat it when it's still on the bone though. I rather eat it in a salad, in a rice dish, in a wrap or something like that.
